---
# Schema for CDN definitions dataset.
#
# This schema is used within autotests to ensure that every published
# revision of the dataset matches the expected structure.
#
# Check the dataset itself for explanatory comments on each field.

$schema: http://json-schema.org/draft-07/schema#
$id: http://release-engineering.github.io/cdn-definitions/schema.json


definitions:
  arch:
    type: string

  arch_list:
    type: array
    items:
      $ref: "#/definitions/arch"
    uniqueItems: true

  release_version:
    type: string
    pattern: "^[0-9]+\\.[0-9]+$"

  major_version:
    type: integer

  major_version_list:
    type: array
    items:
      $ref: "#/definitions/major_version"
    uniqueItems: true

  major_version_string:
    type: string
    pattern: "^[0-9]+$"

  signing_key:
    type: string
    pattern: "^[A-F0-9]{8}$"

  product_id:
    type: string
    pattern: "^[0-9]+$"

  content_set_label:
    type: string
    pattern: "^[A-Za-z0-9_\\-]{1,200}$"

  product_id_list:
    type: array
    items:
      $ref: "#/definitions/product_id"
    uniqueItems: true

  signing_key_list:
    type: array
    items:
      $ref: "#/definitions/signing_key"
    uniqueItems: true

  release_version_list:
    type: array
    items:
      $ref: "#/definitions/release_version"
    uniqueItems: true

  major_or_release_version:
    type: string
    pattern: "^[0-9]+(\\.[0-9]+)*$"

  # various product definition mappings
  version_to_arch_list_mapping:
    type: object
    propertyNames:
      $ref: "#/definitions/major_version_string"
    patternProperties:
      ".*":
        $ref: "#/definitions/arch_list"
    additionalProperties: false

  major_to_release_version_mapping:
    type: object
    propertyNames:
      $ref: "#/definitions/major_version_string"
    patternProperties:
      ".*":
        $ref: "#/definitions/release_version"
    additionalProperties: false

  content_set_to_release_version_mapping:
    type: object
    propertyNames:
      $ref: "#/definitions/content_set_label"
    patternProperties:
      ".*":
        $ref: "#/definitions/release_version"
    additionalProperties: false

  release_stream_mapping:
    type: object
    patternProperties:
      ".*":
        $ref: "#/definitions/release_version_list"
    additionalProperties: false

  current_latest_rhel_versions:
    type: object
    propertyNames:
      type: string
      pattern: "^(current|latest)\\_rhel[0-9]+\\_(beta|dist)$"
    patternProperties:
      ".*":
        anyOf:
        - type: "null"
        - $ref: "#/definitions/release_version"
    additionalProperties: false

  env_to_releasever_mapping:
    type: object
    patternProperties:
      ".*":
        $ref: "#/definitions/current_latest_rhel_versions"
    additionalProperties: false

  # TPS stream configuration
  tps_variant_mapping:
    type: object
    patternProperties:
      ".*":
        type: string
    additionalProperties: false

  # signing keys mappings
  beta_and_ga_keys_mapping:
    type: object
    properties:
      beta_keys:
        $ref: "#/definitions/signing_key_list"
      ga_keys:
        $ref: "#/definitions/signing_key_list"
    required:
    - ga_keys
    additionalProperties: false

  major_version_to_signing_keys_mapping:
    propertyNames:
      $ref: "#/definitions/major_version_string"
    patternProperties:
      ".*":
        $ref: "#/definitions/beta_and_ga_keys_mapping"
    additionalProperties: false

  string_to_signing_keys_mapping:
    patternProperties:
      ".*":
        $ref: "#/definitions/beta_and_ga_keys_mapping"
    additionalProperties: false

  signing_keys_mapping:
    type: object
    properties:
      default:
        $ref: "#/definitions/beta_and_ga_keys_mapping"
      layered_product:
        $ref: "#/definitions/string_to_signing_keys_mapping"
      platform:
        $ref: "#/definitions/string_to_signing_keys_mapping"
      major_version:
        $ref: "#/definitions/major_version_to_signing_keys_mapping"
    required:
    - layered_product
    - platform
    - major_version
    additionalProperties: false

  # misc workarounds
  exclude_versions_from_listings:
    type: array
    items:
      $ref: "#/definitions/release_version"
    uniqueItems: true

  cfme_version_mappings_list:
    type: object
    propertyNames:
      $ref: "#/definitions/major_or_release_version"
    patternProperties:
      ".*":
        $ref: "#/definitions/major_or_release_version"
    additionalProperties: false

  # cdn configuration
  absolute_path:
    type: string
    pattern: "^/"

  path_alias:
    type: object
    properties:
      src:
        $ref: "#/definitions/absolute_path"
      dest:
        $ref: "#/definitions/absolute_path"
    required:
    - src
    - dest
    additionalProperties: false

  path_alias_list:
    type: array
    items:
      $ref: "#/definitions/path_alias"
    uniqueItems: true

  symlink_exception_list:
    type: array
    items:
      $ref: "#/definitions/absolute_path"
    uniqueItems: true

  iso8601_datetime:
    type: string
    anyOf:
      - format: date
      - format: date-time

  repo_override:
    type: object
    properties:
      if_match_id:
        type: string
      if_match_path:
        $ref: "#/definitions/absolute_path"
      if_created_before:
        $ref: "#/definitions/iso8601_datetime"
      if_created_after:
        $ref: "#/definitions/iso8601_datetime"
      key:
        type: string
        minLength: 1
      value:
        type:
          - string
          - boolean
          - number
    allOf:
      - required:
        - key
        - value
      - anyOf:
        - required:
          - if_match_id
        - required:
          - if_match_path
        - required:
          - if_created_before
        - required:
          - if_created_after
    additionalProperties: false

  repo_overrides:
    type: object
    patternProperties:
      ".*":
        type: array
        items:
          $ref: "#/definitions/repo_override"
    additionalProperties: false

  directory_layout:
    type: object
    properties:
      name: 
        type: string
      pattern:
        type: string
      type:
        type: string
      variant:
        type: string
      arch:
        $ref: "#/definitions/arch"
      platform:
        type: string
      major_version:
        $ref: "#/definitions/major_version_string"
      minor_version:
        $ref: "#/definitions/major_version_string"
      rhui:
        type: boolean
      rhelalt:
        type: boolean
      product:
        type: string
      layered_product:
        type: string
      layered_product_version:
        type: string
      repo:
        type: string
    required:
      - name
      - pattern
    additionalProperties: false

  directory_layouts:
    type: array
    items:
      $ref: "#/definitions/directory_layout"
    uniqueItems: true

type: object
properties:

  version:
    type: string
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"

  rhui_alias:
    $ref: "#/definitions/path_alias_list"

  origin_alias:
    $ref: "#/definitions/path_alias_list"

  releasever_alias:
    $ref: "#/definitions/path_alias_list"

  symlink_exceptions:
    $ref: "#/definitions/symlink_exception_list"

  release_stream_mappings:
    $ref: "#/definitions/release_stream_mapping"

  env_to_releasever_mappings:
    $ref: "#/definitions/env_to_releasever_mapping"

  cfme_version_mappings:
    $ref: "#/definitions/cfme_version_mappings_list"

  tps_variant_mappings:
    $ref: "#/definitions/tps_variant_mapping"

  override_initial_rhel_release:
    $ref: "#/definitions/major_to_release_version_mapping"

  override_final_rhel_release:
    $ref: "#/definitions/content_set_to_release_version_mapping"

  filter_arches_from_release:
    $ref: "#/definitions/version_to_arch_list_mapping"

  signing_keys_mappings:
    $ref: "#/definitions/signing_keys_mapping"

  rhel_open_dist:
    $ref: "#/definitions/major_version_list"

  rhui_product_id:
    $ref: "#/definitions/product_id"

  ignore_lp_version_product_ids:
    $ref: "#/definitions/product_id_list"

  exclude_from_listings:
    $ref: "#/definitions/exclude_versions_from_listings"

  populate_ubi_dot_repos:
    type: boolean

  repo_overrides:
    $ref: "#/definitions/repo_overrides"

  directory_layouts:
    $ref: "#/definitions/directory_layouts"

additionalProperties: false
